CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    ingredients TEXT NOT NULL,
    instructions TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    meal_type TEXT NOT NULL,
    isPrivate BOOLEAN DEFAULT true,
    user_id INTEGER
        REFERENCES rk_users(id) ON DELETE CASCADE NOT NULL
);